---
deployment:
  tasks:
    - /bin/chmod o+x /home/taqinorm
    - export DEPLOYPATH=/home/taqinorm/taqinor_app/
    - /bin/cp -R . $DEPLOYPATH
    - /bin/chmod 755 $DEPLOYPATH
    - /bin/chmod -R o+rX $DEPLOYPATH
    - echo 'PassengerAppRoot "/home/taqinorm/taqinor_app"' > $DEPLOYPATH/.htaccess
    - echo 'PassengerBaseURI "/simulator"' >> $DEPLOYPATH/.htaccess
    - echo 'PassengerPython "/home/taqinorm/virtualenv/taqinor_app/3.12/bin/python"' >> $DEPLOYPATH/.htaccess
    - echo 'PassengerAppType wsgi' >> $DEPLOYPATH/.htaccess
    - echo 'PassengerStartupFile app_wsgi.py' >> $DEPLOYPATH/.htaccess
